# Generated by Django 5.1.2 on 2024-12-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id_estudante', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('dt_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('matricula', models.CharField(max_length=6, unique=True)),
                ('periodo', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=20)),
                ('telefone_emergencia', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=100)),
                ('endereço', models.TextField()),
            ],
        ),
    ]
