# Generated by Django 5.1.2 on 2024-12-13 15:07

from django.db import migrations

def create_user(apps, schema_editor):
    User = apps.get_model('app_cart_estudante', 'User')

    User.objects.create(
                username="007053",
                password="AMF@admin",
                email="otaviofd03@gmail.com"
            )

class Migration(migrations.Migration):

    dependencies = [
        ('app_cart_estudante', '0003_user'),
    ]

    operations = [
        migrations.RunPython(create_user),
    ]
